apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql
  namespace: wordpress
  labels:
    app:  mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app:  mysql
    spec:
      containers:
      - name:  mysql
        image:  mysql:5.7
        ports:
        - containerPort:  3306
          name:  mysql
      restartPolicy: Always