  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name:  mysql
    namespace: wordpress
    labels:
      app:  mysql
  spec:
    selector:
      matchLabels:
        app: mysql
    replicas: 1
    template:
      metadata:
        labels:
          app:  mysql
      spec:
        containers:
        - name:  mysql
          image:  mysql:5.7
          ports:
          - containerPort:  3306
            name:  mysql
          env:
          - name:  MYSQL_ROOT_PASSWORD
            value:  password
          - name:  MYSQL_DATABASE
            value:  wordpress
          - name:  MYSQL_USER 
            value:  wordpress
          - name:  MYSQL_PASSWORD 
            value:  password
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        restartPolicy: Always